# Generated by Django 2.2.3 on 2019-07-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_verses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('verse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mem_app.Verse')),
            ],
        ),
    ]
